FROM python:3.11-slim

WORKDIR /app

# Copiar requirements e instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código del producer
COPY producer.py .

# Comando por defecto
CMD ["python", "-u", "producer.py"]
